import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copyPlugin = {
	name: 'copy-to-vaults',
	setup(build) {
		build.onEnd(() => {
			const destinations = [
				"/Users/xy/Library/Mobile Documents/iCloud~md~obsidian/Documents/bfcs/.obsidian/plugins/obsidian-file-editor",
				"/Users/xy/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian-demo/.obsidian/plugins/obsidian-file-editor"
			];
			const filesToCopy = [
				"main.js",
				"manifest.json",
				"styles.css"
			];
			
			destinations.forEach(dest => {
				try {
					if (!fs.existsSync(dest)) {
						fs.mkdirSync(dest, { recursive: true });
					}
					filesToCopy.forEach(file => {
						if (fs.existsSync(file)) {
							const destPath = path.join(dest, file);
							if (fs.existsSync(destPath)) {
								fs.unlinkSync(destPath);
							}
							fs.linkSync(file, destPath);
							console.log(`[CopyPlugin] Hard-linked ${file} to ${dest}`);
						}
					});
				} catch (err) {
					console.error(`[CopyPlugin] Failed to link to ${dest}:`, err);
				}
			});

			// Trigger Obsidian vault reload synchronously
			try {
				execSync("obsidian reload");
				console.log("[CopyPlugin] Obsidian reload triggered successfully");
			} catch (err) {
				console.error("[CopyPlugin] Failed to reload Obsidian:", err.message);
			}
		});
	}
};



const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

